### ISSUE TITLE
Switch the default readme to Japanese

### ISSUE THREAD

**Issue by mitosagi** [hal-shu-sato/apm#118]
## Is your feature request related to a problem? Please describe.

The default readme for APM is in English. I believe that the majority of aviutl users are Japanese speakers. It may not be comfortable for people who are new to APM to see English.

## Describe the solution you'd like

Switch the default readme to Japanese.

## Additional context

What do you think about this?

**Comment by hal-shu-sato** [comment]
Umm, certainly...
It will be good for users.
Let's do that.
