### ISSUE TITLE
Sometimes high load

### ISSUE THREAD

**Issue by hal-shu-sato** [hal-shu-sato/apm#143]
## Describe the bug

Sometimes, apm puts a high load on the CPU.
But I don't know why it happens.
Please let me know if the same thing happens or if you find the reason.

## To Reproduce

I don't know why it happens.
All I know is that apm continues to run with a high load even after closing.

## Expected behavior

apm doesn't put a high load on the CPU.

## Desktop (please complete the following information):

- OS: Windows 10 Home
- Version: 21H1

**Comment by mitosagi** [comment]
It happened to me too. 4 electron processes were using 100% of the CPU even after APM exited. I will check it out.

**Comment by mitosagi** [comment]
This bug can be reproduced by adding `throw new Error();` after `createSplash();` on `main.js:385` and before `app.on('activate', () => {` on `main.js:388`.

**Comment by mitosagi** [comment]
Also, this happens in ad62aee5bf5d4949397fafdad8d8b3a479279335 and not in a6664df3d3e36d90f58e71380a4beb56a42ae09c after updating to Electron14. Therefore, it may not happen in the future.
