### ISSUE TITLE
ビルド者の表示

### ISSUE THREAD

**Issue by yumetodo** [hal-shu-sato/apm#174]
## 問題点

例えばL-SMASH Workdは公式ではバイナリは頒布されていない。またリンクするffmepgによっても挙動が変わる。誰のどのビルドなのか実際にインストールしないとわからない

## 提案する解決方法

プラグイン/スクリプト管理画面にビルド者のカラムを追加する

**Comment by hal-shu-sato** [comment]
カラムの追加には、スペースの問題があるのは同意します。
なんらかの方法でビルド者を示す必要はありそうです。
builder要素をオプションで追加して、apm側で表示の判定をするのはどうでしょうか。
