### ISSUE TITLE
Use SRI

### ISSUE THREAD

**Issue by hal-shu-sato** [hal-shu-sato/apm#235]
## Is your feature request related to a problem? Please describe.

- Estimating the version of the package installed manually is useful.
- Checking the integrity of the files is good for stability.

## Describe the solution you'd like

- Estimate the version from the hash. (This feature is added by @mitosagi.)
- Check the integrity of the files from the hash.

## Additional context

Now, integrity is added in apm-data v1, but apm supporting it has not been released now.
So, I suggest deleting integrity from v1 and supporting it on v2.
This is to save the effort of maintenance.

**Comment by mitosagi** [comment]
> Check the integrity of the files from the hash.

Is this to verify the integrity of the download file? Or is it to detect inconsistencies in package versions?

**Comment by hal-shu-sato** [comment]
I think it means both and both are needed.
Especially checking an archive file is needed in order not to install falsified files.

**Comment by mitosagi** [comment]
It would be difficult to do it for all packages due to the data maintenance effort, so I would like to implement it only for archives created by KEN or archives that are downloaded directly.

**Comment by hal-shu-sato** [comment]
Well, that's certainly true...
Let's do that.
