### ISSUE TITLE
ESModule

### ISSUE THREAD

**Issue by hal-shu-sato** [hal-shu-sato/apm#315]
## Is your feature request related to a problem? Please describe.

Some packages use ESModule and apm can't use them now.
Also, the use of ESModule is slowly becoming mainstream.
And, I heard ESModule can import CommonJS Module too.

## Describe the solution you'd like

Use ESModule.

**Comment by mitosagi** [comment]
Dependencies that cannot be upgraded because they are only compatible with ESM
- https://github.com/hal-shu-sato/apm/pull/335

**Comment by mitosagi** [comment]
This issue has been resolved by https://github.com/hal-shu-sato/apm/pull/344#issuecomment-1078709171 .
