### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by hal-shu-sato** [hal-shu-sato/apm#321]
## Is your feature request related to a problem? Please describe.

An organization has more functions than a personal repository.
I think that if this project becomes bigger, I should make an organization.

**Comment by mitosagi** [comment]
I don't want to keep apm-web for myself, so I'll move it to Organization if it's available.

**Comment by hal-shu-sato** [comment]
Oh, I see.
Should I make it soon?
(But I don't have a good name for an organization because `apm` and `apm-team` are already taken...)

**Comment by mitosagi** [comment]
We'll think about it later.

**Comment by mitosagi** [comment]
How about team-apm?

**Comment by hal-shu-sato** [comment]
I made it for now to get an ID as well.

**Comment by hal-shu-sato** [comment]
I love the name Team apm.
Let's use this name.
I sent an invitation to the org to you.
Could you join the org?

**Comment by hal-shu-sato** [comment]
Before transferring the ownership of this repository, we MUST release apm including this code.

- `update-electron-app` find repository URL in `package.json` so change the URL.
https://github.com/electron/update-electron-app#usage
https://github.com/hal-shu-sato/apm/blob/7b33ab41fea8f15046aeeb46aa52b676b9edaed6/package.json#L7
```json
 "repository": "https://github.com/team-apm/apm.git",
```

Just to be sure, we should change below:
https://github.com/hal-shu-sato/apm/blob/7b33ab41fea8f15046aeeb46aa52b676b9edaed6/forge.config.js#L69-L72
```js
 repository: {
   owner: 'team-apm',
   name: 'apm',
 },
```

**Comment by hal-shu-sato** [comment]
I'd like to release apm including this patch.
And after that, I'll transfer this repository and hal-shu-sato/apm-data to team-apm.

**Comment by mitosagi** [comment]
After the transfer, you will need to access https://cdn.jsdelivr.net/gh/team-apm/apm-data@main/v2/data/ to generate a cache. Once cached, you can update the jsdelivr URL in the apm.

**Comment by hal-shu-sato** [comment]
I'll transfer this repository to `team-apm` a week after I release `v2.2.0`.
I think almost all GitHub features will work fine by a redirect.
