### ISSUE TITLE
Add zip download button in the website / サイトにzipのダウンロードボタンを追加する

### ISSUE THREAD

**Issue by pklion** [hal-shu-sato/apm#416]
## 問題点
公式サイトからのインストール時にzip形式のダウンロードが選べず残念に思っています。

## 提案する解決方法
公式サイトにzip形式のダウンロードボタンを追加していただきたいです。

## 検討した代替案
少なくともダウンロードするのがexe形式であることがわかるだけでも個人的にはうれしいです。

## 補足説明
あくまでイメージですが。
![image](https://user-images.githubusercontent.com/78145811/159115303-5484cadc-38db-465f-9253-280af3b3456d.png)

**Comment by hal-shu-sato** [comment]
確かにそうですね。
追加しておきます。

**Comment by pklion** [comment]
ありがとうございます
