### ISSUE TITLE
Add "Check updates" button in the app / 更新確認のボタンをつける

### ISSUE THREAD

**Issue by pklion** [hal-shu-sato/apm#417]
## 問題点
APMの更新を確認するために、わざわざこのページを訪れるのは手間がかかります。

## 提案する解決方法
更新確認のボタンをつけていただきたいです。

## 検討した代替案
自動で更新の確認をすることもできるかとは思うのですが、煙たがられることも多いようなので。

**Comment by hal-shu-sato** [comment]
update.electronjs.org を利用して、更新があった時にお知らせダイアログを表示することができそうです。
また、自動更新のオン/オフも、切り替えられるようになるとよさそうですね。
