### ISSUE TITLE
Remove menu bar / メニューバーを廃止する

### ISSUE THREAD

**Issue by pklion** [hal-shu-sato/apm#418]
## 問題点
上部メニューバーにある"apm"のラベルのメニューは中のメニューの内容が想像しにくく、かつあまりデザインとしても下のタブ選択部分と統一感がないように感じます。

## 提案する解決方法
補足説明の図のように、"apm"としてかつておかれていた項目を、Aboutタブの中に入れるというのはいかがでしょうか。
内部の項目がより想像しやすく、デザインとしても統一感が生まれるのではないかと考えます。

## 検討した代替案
メニューのラベルを変更していただくだけでもありがたいです。

## 補足説明
![image](https://user-images.githubusercontent.com/78145811/159116147-d7c2df71-7f68-46ca-9f53-d5087d024419.png)

**Comment by hal-shu-sato** [comment]
確かにそうですね。
やりましょう。
