### ISSUE TITLE
Support a large number of plug-ins

### ISSUE THREAD

**Issue by mitosagi** [hal-shu-sato/apm#65]
## Is your feature request related to a problem? Please describe.

In order to make APM even more useful, we will need to support a lot of famous plugins.

## Describe the solution you'd like

The work includes finding, validating, and entering data for the plugins. @hal-shu-sato Is it possible to maintain the list of plugins as a Github repository to do these things?

**Comment by hal-shu-sato** [comment]
I think so too.
Rather, I was thinking about what to do about it, and forgot about it.
I was kind of thinking of a wiki-style thing, but I was worried about it being vandalized.
Surely with GitHub, it can be controlled by PR.
I'll prepare the repository.

**Comment by mitosagi** [comment]
Thanks for the reply. It helps a lot.

**Comment by hal-shu-sato** [comment]
I made it.
https://github.com/hal-shu-sato/apm-data

**Comment by mitosagi** [comment]
Thank you for creating the repository. I would like to start adding plugins.

Close this issue in favor of the solution.
