### ISSUE TITLE
Refactoring plugin.js and scripts.js as a whole

### ISSUE THREAD

**Issue by hal-shu-sato** [hal-shu-sato/apm#70]
## Is your feature request related to a problem? Please describe.

These files use similar processes.
So, refactoring will help development.

## Describe the solution you'd like

Refactor similar processes of `plugin.js` and `scripts.js`.

**Comment by mitosagi** [comment]
I was thinking about this when I was entering data for oov's PSDToolKit, which has both plugins and scripts attached to it. Is it necessary to separate the plugins and scripts? I think if you use a filter button to separate script and plugin, there is no need for multiple xml files or code.

**Comment by hal-shu-sato** [comment]
I am thinking so too these days.
I once thought that different processes were needed between plugins and scripts.
But I found they are very similar ones.
It is a good idea to integrate their processes.
