### ISSUE TITLE
Read the README in APM

### ISSUE THREAD

**Issue by mitosagi** [hal-shu-sato/apm#76]
## Is your feature request related to a problem? Please describe.

It is difficult to find and read the readme for plugins installed through APM.

## Describe the solution you'd like

Add a button to the plugin list to read the readme for the selected plugin. The readme file will be searched for in the extracted folder by pattern matching.

## Describe alternatives you've considered

Add a button to open the extracted folder of the plugin.

**Comment by mitosagi** [comment]
I tried to implement this, but the feature to open the Readme and license of the package directly was not very useful, even though it makes the code more complicated. Instead, I will consider to add the feature to open the download folder of the package.

**Comment by hal-shu-sato** [comment]
This assignment is just to show your effort.
