### ISSUE TITLE
Sites with older SSL versions

### ISSUE THREAD

**Issue by mitosagi** [hal-shu-sato/apm#80]
## Describe the bug

When I try to install "DirectShow File Reader プラグイン for AviUtl", I get the following error message.

```
electron: Failed to load URL: https://videoinfo.tenchi.ne.jp/?DirectShow%20File%20Reader%20%A5%D7%A5%E9%A5%B0%A5%A4%A5%F3%20for%20AviUtl with error: ERR_SSL_OBSOLETE_VERSION
```

## To Reproduce

1.  Install "DirectShow File Reader プラグイン for AviUtl".

## Expected behavior

The plugin will be installed.

## Desktop (please complete the following information):

- OS: Windows 11
- Version:  22000.160

## Additional context

You need to either remove this plugin or [ignore the warning](https://stackoverflow.com/questions/44658269/electron-how-to-allow-insecure-https). Since apm has no problem working with http, I consider it safe to ignore the warning.

**Comment by hal-shu-sato** [comment]
Thank you for pointing this out.
I feel it's not a good idea for apm to ignore warnings and put users at risk.
I think it would be better to show a confirmation dialog asking if the connection should continue.

**Comment by mitosagi** [comment]
Certainly it is dangerous to ignore it. I' ll implement it in the way of displaying a dialog.

**Comment by hal-shu-sato** [comment]
I found a document that may be useful for this improvement.
If it's good, please make use of it.
https://www.electronjs.org/docs/latest/api/web-contents#event-certificate-error
